name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: current-alpine3.10 
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
